# PostgreSQL. Versions 9.1 and up are supported.
default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: quasi_case_exam_development

test:
  <<: *default
  database: quasi_case_exam_test

staging:
  <<: *default
  database: quasi_case_exam_staging
  username: staging_user
  password: <%= ENV['MY_PRESET_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: quasi_case_exam_production
  username: quasi_case_exam_
  password: <%= ENV['MY_PRESET_DATABASE_PASSWORD'] %>
